### ISSUE TITLE
Appleskin doesn't work on JEI

### ISSUE THREAD

**Issue by ErayGunes** [squeek502/AppleSkin#326]
Hello first of all sorry for my bad English.

I have AppleSkin mod it shows food stats on inventory tooltip. But it doesn't work on JEI.

![1](https://github.com/user-attachments/assets/34158feb-a068-43db-9526-bd558ee394be)
![2](https://github.com/user-attachments/assets/82ea52ec-841f-41db-a7e8-7ec2747dc1c2)

**Comment by squeek502** [comment]
What mod loader? What version of JEI?

If it's the same problem as https://github.com/squeek502/AppleSkin/issues/314, then updating your JEI might fix it.

**Comment by ErayGunes** [comment]
Fabric

jei-1.21.1-fabric-19.16.4.165

And i installed EMI Mod for JEI. The problem was fixed.

**Comment by BoxieBoomkin** [comment]
Using **appleskin-fabric-mc1.21-3.0.5** and **jei-1.21.1-fabric-19.19.6.236** (latest available version) and encountering the same issue. No food values shown in JEI's recipe pane.
Swapped to **jei-1.21.1-fabric-19.21.0.246** (Beta version) but issue persists. Food values shown in creative pane but not recipe viewer.
Also downgraded to **jei-1.21.1-fabric-19.8.4.113** (Release version) but still no hunger values in recipe pane.

No other versions of Appleskin to test.

**Comment by squeek502** [comment]
Found the cause, not yet sure how to fix it. Details are here: https://github.com/mezz/JustEnoughItems/issues/3626#issuecomment-2444627688

**Comment by squeek502** [comment]
Should be fixed in AppleSkin v3.0.6 for 1.21/1.21.1

Note: This will currently still be broken in the 1.21.3 version, will need to release an AppleSkin update for that once JEI updates to 1.21.3

**Comment by Pandoroeo** [comment]
Will there every be a fix for 1.20.1? Or is there some workaround I can implement myself to fix it (as in copy and paste it lol)? Thanks!

**Comment by squeek502** [comment]
Didn't realize those JEI changes got backported to 1.20.1. Will look into releasing a 1.20.1 version with a fix.

**Comment by Pandoroeo** [comment]
> Didn't realize those JEI changes got backported to 1.20.1. 

Not sure if they did
> Will look into releasing a 1.20.1 version with a fix.

Thank you! This has been just the slight bit of an annoyance lol. You are doing great work :D

**Comment by Noah-Dekka** [comment]
I think this issue is reappearing on appleskin-fabric-mc1.21.11-3.0.7 with fabric-api-0.141.1+1.21.11.jar on fabric loader 0.18.4.

**Comment by squeek502** [comment]
Yep, will have a fixed version out within the next day or two

**Comment by squeek502** [comment]
Fixed in v2.5.2 (for 1.20.1) and v3.0.8 (for 1.21.11)
